name: Build and Release RAD Cross-Platform

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons

      - name: Check for signing secrets
        id: check_secrets
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ] && \
             [ -n "${{ secrets.KEYSTORE_PASSWORD }}" ] && \
             [ -n "${{ secrets.KEY_ALIAS }}" ] && \
             [ -n "${{ secrets.KEY_PASSWORD }}" ]; then
            echo "secrets_present=true" >> $GITHUB_OUTPUT
          else
            echo "secrets_present=false" >> $GITHUB_OUTPUT
            echo "::warning::Signing secrets not found. Skipping release build signing."
          fi
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Decode Keystore & Create key.properties
        if: steps.check_secrets.outputs.secrets_present == 'true'
        run: |
          echo "Decoding Keystore..."
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks
          echo "Creating key.properties..."
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build Android Release APK
        if: steps.check_secrets.outputs.secrets_present == 'true'
        run: flutter build apk --release

      - name: Upload Android APK Artifact
        if: steps.check_secrets.outputs.secrets_present == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: radcxp-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx # Give the buildx setup step an id to reference its outputs
        uses: docker/setup-buildx-action@v3

      - name: Build Linux ARM64 Release (Docker with Buildx)
        run: |
          # Use docker buildx build to build the image for linux/arm64
          # This command replicates the core action of build_linux_arm.sh
          # but uses buildx for cross-platform building.
          docker buildx build \
            --platform linux/arm64 \
            --tag radcxp-linux-builder-alpine-arm:latest \
            --output type=local,dest=./build/linux-arm64-release \
            --file Dockerfile.linux-arm \
            .

      - name: Package Linux ARM64 Artifacts
        id: package_linux
        run: |
          # Extract version from pubspec.yaml (e.g., 1.0.0+1 -> 1.0.0)
          APP_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //g' | sed 's/+.*//')
          echo "App Version: $APP_VERSION"
          # Define archive name with version
          ARCHIVE_NAME="radcxp-linux-arm64-v${APP_VERSION}.tar.gz"
          echo "Archive Name: $ARCHIVE_NAME"
          # Create the tarball
          tar -czvf ${ARCHIVE_NAME} -C build/linux-arm64-release .
          # Set output variable for the archive name
          echo "archive_name=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT

      - name: Upload Linux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: radcxp-linux-arm64-tarball
          path: ${{ steps.package_linux.outputs.archive_name }}
          retention-days: 7

      - name: Validate Version Tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Extract version from pubspec.yaml (e.g., 1.0.0+1 -> 1.0.0)
          PUB_VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //g' | sed 's/+.*//')
          # Extract version from tag (e.g., refs/tags/v1.0.0 -> 1.0.0)
          TAG_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')

          echo "Pubspec Version: $PUB_VERSION"
          echo "Tag Version: $TAG_VERSION"

          if [ "$PUB_VERSION" != "$TAG_VERSION" ]; then
            echo "::error::Tag version ($TAG_VERSION) does not match pubspec.yaml version ($PUB_VERSION)."
            exit 1
          fi
          echo "Version tag matches pubspec.yaml."

      - name: Create GitHub Release and Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          # Optional: Add release notes or mark as pre-release
          # body: |
          #   Release notes for ${{ github.ref_name }}
          # prerelease: false
          draft: false # Create as a published release
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            ${{ steps.package_linux.outputs.archive_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
